package simconnect

// EventCatalog is a comprehensive list of known SimConnect events.
var EventCatalog = []EventInfo{
	// Landing Gear
	{Name: "GEAR_UP", Category: "Gear", Description: "Retract landing gear"},
	{Name: "GEAR_DOWN", Category: "Gear", Description: "Extend landing gear"},
	{Name: "GEAR_TOGGLE", Category: "Gear", Description: "Toggle landing gear"},
	{Name: "GEAR_SET", Category: "Gear", Description: "Set gear position (0=up, 1=down)", HasParam: true},
	{Name: "GEAR_PUMP", Category: "Gear", Description: "Pump gear handle (emergency extension)"},

	// Flaps
	{Name: "FLAPS_UP", Category: "Flaps", Description: "Retract flaps fully"},
	{Name: "FLAPS_DOWN", Category: "Flaps", Description: "Extend flaps fully"},
	{Name: "FLAPS_INCR", Category: "Flaps", Description: "Increase flaps one notch"},
	{Name: "FLAPS_DECR", Category: "Flaps", Description: "Decrease flaps one notch"},
	{Name: "FLAPS_SET", Category: "Flaps", Description: "Set flaps to position (0-16383)", HasParam: true},
	{Name: "FLAPS_1", Category: "Flaps", Description: "Set flaps to position 1"},
	{Name: "FLAPS_2", Category: "Flaps", Description: "Set flaps to position 2"},
	{Name: "FLAPS_3", Category: "Flaps", Description: "Set flaps to position 3"},

	// Spoilers
	{Name: "SPOILERS_ON", Category: "Spoilers", Description: "Deploy spoilers fully"},
	{Name: "SPOILERS_OFF", Category: "Spoilers", Description: "Retract spoilers"},
	{Name: "SPOILERS_TOGGLE", Category: "Spoilers", Description: "Toggle spoilers"},
	{Name: "SPOILERS_SET", Category: "Spoilers", Description: "Set spoiler position (0-16383)", HasParam: true},
	{Name: "SPOILERS_ARM_ON", Category: "Spoilers", Description: "Arm spoilers"},
	{Name: "SPOILERS_ARM_OFF", Category: "Spoilers", Description: "Disarm spoilers"},
	{Name: "SPOILERS_ARM_TOGGLE", Category: "Spoilers", Description: "Toggle spoiler arm"},

	// Brakes
	{Name: "BRAKES", Category: "Brakes", Description: "Apply brakes momentarily"},
	{Name: "BRAKES_LEFT", Category: "Brakes", Description: "Apply left brake"},
	{Name: "BRAKES_RIGHT", Category: "Brakes", Description: "Apply right brake"},
	{Name: "PARKING_BRAKES", Category: "Brakes", Description: "Toggle parking brake"},
	{Name: "PARKING_BRAKE_SET", Category: "Brakes", Description: "Set parking brake (1=on, 0=off)", HasParam: true},
	{Name: "AUTOBRAKES_DISARM", Category: "Brakes", Description: "Disarm autobrakes"},
	{Name: "AUTOBRAKES_LOW", Category: "Brakes", Description: "Set autobrakes to low"},
	{Name: "AUTOBRAKES_MED", Category: "Brakes", Description: "Set autobrakes to medium"},
	{Name: "AUTOBRAKES_HIGH", Category: "Brakes", Description: "Set autobrakes to high"},
	{Name: "AUTOBRAKES_MAX", Category: "Brakes", Description: "Set autobrakes to max/RTO"},

	// Throttle
	{Name: "THROTTLE_FULL", Category: "Throttle", Description: "Set throttle to full power"},
	{Name: "THROTTLE_CUT", Category: "Throttle", Description: "Set throttle to idle/cutoff"},
	{Name: "THROTTLE_SET", Category: "Throttle", Description: "Set throttle position (0-16383)", HasParam: true},
	{Name: "THROTTLE_INCR", Category: "Throttle", Description: "Increase throttle"},
	{Name: "THROTTLE_DECR", Category: "Throttle", Description: "Decrease throttle"},
	{Name: "THROTTLE_INCR_SMALL", Category: "Throttle", Description: "Increase throttle small amount"},
	{Name: "THROTTLE_DECR_SMALL", Category: "Throttle", Description: "Decrease throttle small amount"},
	{Name: "THROTTLE1_SET", Category: "Throttle", Description: "Set engine 1 throttle (0-16383)", HasParam: true},
	{Name: "THROTTLE2_SET", Category: "Throttle", Description: "Set engine 2 throttle (0-16383)", HasParam: true},
	{Name: "THROTTLE3_SET", Category: "Throttle", Description: "Set engine 3 throttle (0-16383)", HasParam: true},
	{Name: "THROTTLE4_SET", Category: "Throttle", Description: "Set engine 4 throttle (0-16383)", HasParam: true},
	{Name: "THROTTLE_REVERSE_THRUST_TOGGLE", Category: "Throttle", Description: "Toggle reverse thrust"},
	{Name: "THROTTLE1_FULL", Category: "Throttle", Description: "Engine 1 throttle full"},
	{Name: "THROTTLE1_CUT", Category: "Throttle", Description: "Engine 1 throttle idle"},
	{Name: "THROTTLE2_FULL", Category: "Throttle", Description: "Engine 2 throttle full"},
	{Name: "THROTTLE2_CUT", Category: "Throttle", Description: "Engine 2 throttle idle"},

	// Engine
	{Name: "ENGINE_AUTO_START", Category: "Engine", Description: "Auto-start all engines"},
	{Name: "ENGINE_AUTO_SHUTDOWN", Category: "Engine", Description: "Auto-shutdown all engines"},
	{Name: "FUEL_PUMP", Category: "Engine", Description: "Toggle fuel pump"},
	{Name: "MAGNETO_OFF", Category: "Engine", Description: "Magnetos off"},
	{Name: "MAGNETO_RIGHT", Category: "Engine", Description: "Magnetos right only"},
	{Name: "MAGNETO_LEFT", Category: "Engine", Description: "Magnetos left only"},
	{Name: "MAGNETO_BOTH", Category: "Engine", Description: "Magnetos both"},
	{Name: "MAGNETO_START", Category: "Engine", Description: "Magneto start position"},
	{Name: "MAGNETO1_OFF", Category: "Engine", Description: "Engine 1 magnetos off"},
	{Name: "MAGNETO1_BOTH", Category: "Engine", Description: "Engine 1 magnetos both"},
	{Name: "MAGNETO1_START", Category: "Engine", Description: "Engine 1 magneto start"},
	{Name: "MAGNETO2_OFF", Category: "Engine", Description: "Engine 2 magnetos off"},
	{Name: "MAGNETO2_BOTH", Category: "Engine", Description: "Engine 2 magnetos both"},
	{Name: "MAGNETO2_START", Category: "Engine", Description: "Engine 2 magneto start"},
	{Name: "STARTER1_SET", Category: "Engine", Description: "Set engine 1 starter", HasParam: true},
	{Name: "STARTER2_SET", Category: "Engine", Description: "Set engine 2 starter", HasParam: true},
	{Name: "STARTER3_SET", Category: "Engine", Description: "Set engine 3 starter", HasParam: true},
	{Name: "STARTER4_SET", Category: "Engine", Description: "Set engine 4 starter", HasParam: true},
	{Name: "ENGINE_PRIMER", Category: "Engine", Description: "Engine primer"},

	// Fuel System
	{Name: "FUEL_SELECTOR_ALL", Category: "Fuel", Description: "Fuel selector to ALL tanks"},
	{Name: "FUEL_SELECTOR_LEFT", Category: "Fuel", Description: "Fuel selector to left tank"},
	{Name: "FUEL_SELECTOR_RIGHT", Category: "Fuel", Description: "Fuel selector to right tank"},
	{Name: "FUEL_SELECTOR_OFF", Category: "Fuel", Description: "Fuel selector off"},
	{Name: "FUEL_SELECTOR_SET", Category: "Fuel", Description: "Set fuel selector position", HasParam: true},
	{Name: "CROSS_FEED_TOGGLE", Category: "Fuel", Description: "Toggle fuel crossfeed valve"},
	{Name: "CROSS_FEED_OPEN", Category: "Fuel", Description: "Open fuel crossfeed valve"},
	{Name: "CROSS_FEED_OFF", Category: "Fuel", Description: "Close fuel crossfeed valve"},
	{Name: "FUEL_DUMP_TOGGLE", Category: "Fuel", Description: "Toggle fuel dump"},

	// Mixture
	{Name: "MIXTURE_RICH", Category: "Mixture", Description: "Full rich mixture"},
	{Name: "MIXTURE_LEAN", Category: "Mixture", Description: "Full lean mixture"},
	{Name: "MIXTURE_INCR", Category: "Mixture", Description: "Increase mixture"},
	{Name: "MIXTURE_DECR", Category: "Mixture", Description: "Decrease mixture"},
	{Name: "MIXTURE_INCR_SMALL", Category: "Mixture", Description: "Increase mixture small amount"},
	{Name: "MIXTURE_DECR_SMALL", Category: "Mixture", Description: "Decrease mixture small amount"},
	{Name: "MIXTURE_SET", Category: "Mixture", Description: "Set mixture (0-16383)", HasParam: true},
	{Name: "MIXTURE1_SET", Category: "Mixture", Description: "Set engine 1 mixture (0-16383)", HasParam: true},
	{Name: "MIXTURE2_SET", Category: "Mixture", Description: "Set engine 2 mixture (0-16383)", HasParam: true},
	{Name: "MIXTURE_SET_BEST", Category: "Mixture", Description: "Set mixture to best power"},

	// Propeller
	{Name: "PROP_PITCH_HI", Category: "Propeller", Description: "Propeller high RPM"},
	{Name: "PROP_PITCH_LO", Category: "Propeller", Description: "Propeller low RPM / feather"},
	{Name: "PROP_PITCH_INCR", Category: "Propeller", Description: "Increase prop RPM"},
	{Name: "PROP_PITCH_DECR", Category: "Propeller", Description: "Decrease prop RPM"},
	{Name: "PROP_PITCH_INCR_SMALL", Category: "Propeller", Description: "Increase prop RPM small amount"},
	{Name: "PROP_PITCH_DECR_SMALL", Category: "Propeller", Description: "Decrease prop RPM small amount"},
	{Name: "PROP_PITCH_SET", Category: "Propeller", Description: "Set prop pitch (0-16383)", HasParam: true},
	{Name: "PROP_PITCH1_SET", Category: "Propeller", Description: "Set engine 1 prop pitch (0-16383)", HasParam: true},
	{Name: "PROP_PITCH2_SET", Category: "Propeller", Description: "Set engine 2 prop pitch (0-16383)", HasParam: true},

	// Anti-Ice
	{Name: "PITOT_HEAT_ON", Category: "Anti-Ice", Description: "Turn pitot heat on"},
	{Name: "PITOT_HEAT_OFF", Category: "Anti-Ice", Description: "Turn pitot heat off"},
	{Name: "PITOT_HEAT_TOGGLE", Category: "Anti-Ice", Description: "Toggle pitot heat"},
	{Name: "ANTI_ICE_TOGGLE", Category: "Anti-Ice", Description: "Toggle structural anti-ice"},
	{Name: "ANTI_ICE_ON", Category: "Anti-Ice", Description: "Turn anti-ice on"},
	{Name: "ANTI_ICE_OFF", Category: "Anti-Ice", Description: "Turn anti-ice off"},
	{Name: "ANTI_ICE_SET", Category: "Anti-Ice", Description: "Set anti-ice (1=on, 0=off)", HasParam: true},
	{Name: "CARB_HEAT_TOGGLE", Category: "Anti-Ice", Description: "Toggle carburetor heat"},
	{Name: "ENG_ANTI_ICE_TOGGLE", Category: "Anti-Ice", Description: "Toggle engine anti-ice"},
	{Name: "WINDSHIELD_DEICE_ON", Category: "Anti-Ice", Description: "Turn windshield deice on"},
	{Name: "WINDSHIELD_DEICE_OFF", Category: "Anti-Ice", Description: "Turn windshield deice off"},
	{Name: "WINDSHIELD_DEICE_TOGGLE", Category: "Anti-Ice", Description: "Toggle windshield deice"},

	// Trim
	{Name: "ELEV_TRIM_UP", Category: "Trim", Description: "Pitch trim up (nose up)"},
	{Name: "ELEV_TRIM_DN", Category: "Trim", Description: "Pitch trim down (nose down)"},
	{Name: "ELEVATOR_TRIM_SET", Category: "Trim", Description: "Set elevator trim (-16383 to 16383)", HasParam: true},
	{Name: "RUDDER_TRIM_LEFT", Category: "Trim", Description: "Rudder trim left"},
	{Name: "RUDDER_TRIM_RIGHT", Category: "Trim", Description: "Rudder trim right"},
	{Name: "RUDDER_TRIM_SET", Category: "Trim", Description: "Set rudder trim (-16383 to 16383)", HasParam: true},
	{Name: "AILERON_TRIM_LEFT", Category: "Trim", Description: "Aileron trim left"},
	{Name: "AILERON_TRIM_RIGHT", Category: "Trim", Description: "Aileron trim right"},
	{Name: "AILERON_TRIM_SET", Category: "Trim", Description: "Set aileron trim (-16383 to 16383)", HasParam: true},

	// Autopilot
	{Name: "AP_MASTER", Category: "Autopilot", Description: "Toggle autopilot master"},
	{Name: "AUTOPILOT_ON", Category: "Autopilot", Description: "Turn autopilot on"},
	{Name: "AUTOPILOT_OFF", Category: "Autopilot", Description: "Turn autopilot off"},
	{Name: "AP_ALT_HOLD", Category: "Autopilot", Description: "Toggle altitude hold mode"},
	{Name: "AP_ALT_HOLD_ON", Category: "Autopilot", Description: "Turn altitude hold on"},
	{Name: "AP_ALT_HOLD_OFF", Category: "Autopilot", Description: "Turn altitude hold off"},
	{Name: "AP_ALT_VAR_SET_ENGLISH", Category: "Autopilot", Description: "Set altitude bug (feet)", HasParam: true},
	{Name: "AP_ALT_VAR_INC", Category: "Autopilot", Description: "Increase altitude bug"},
	{Name: "AP_ALT_VAR_DEC", Category: "Autopilot", Description: "Decrease altitude bug"},
	{Name: "AP_HDG_HOLD", Category: "Autopilot", Description: "Toggle heading hold mode"},
	{Name: "AP_HDG_HOLD_ON", Category: "Autopilot", Description: "Turn heading hold on"},
	{Name: "AP_HDG_HOLD_OFF", Category: "Autopilot", Description: "Turn heading hold off"},
	{Name: "HEADING_BUG_SET", Category: "Autopilot", Description: "Set heading bug (degrees)", HasParam: true},
	{Name: "HEADING_BUG_INC", Category: "Autopilot", Description: "Increase heading bug"},
	{Name: "HEADING_BUG_DEC", Category: "Autopilot", Description: "Decrease heading bug"},
	{Name: "AP_NAV1_HOLD", Category: "Autopilot", Description: "Toggle NAV hold mode"},
	{Name: "AP_NAV1_HOLD_ON", Category: "Autopilot", Description: "Turn NAV hold on"},
	{Name: "AP_NAV1_HOLD_OFF", Category: "Autopilot", Description: "Turn NAV hold off"},
	{Name: "AP_APR_HOLD", Category: "Autopilot", Description: "Toggle approach mode"},
	{Name: "AP_APR_HOLD_ON", Category: "Autopilot", Description: "Turn approach mode on"},
	{Name: "AP_APR_HOLD_OFF", Category: "Autopilot", Description: "Turn approach mode off"},
	{Name: "AP_VS_HOLD", Category: "Autopilot", Description: "Toggle vertical speed hold"},
	{Name: "AP_VS_ON", Category: "Autopilot", Description: "Turn VS hold on"},
	{Name: "AP_VS_OFF", Category: "Autopilot", Description: "Turn VS hold off"},
	{Name: "AP_VS_VAR_SET_ENGLISH", Category: "Autopilot", Description: "Set vertical speed (fpm)", HasParam: true},
	{Name: "AP_VS_VAR_INC", Category: "Autopilot", Description: "Increase VS target"},
	{Name: "AP_VS_VAR_DEC", Category: "Autopilot", Description: "Decrease VS target"},
	{Name: "AP_AIRSPEED_HOLD", Category: "Autopilot", Description: "Toggle speed hold mode"},
	{Name: "AP_AIRSPEED_ON", Category: "Autopilot", Description: "Turn speed hold on"},
	{Name: "AP_AIRSPEED_OFF", Category: "Autopilot", Description: "Turn speed hold off"},
	{Name: "AP_SPD_VAR_SET", Category: "Autopilot", Description: "Set speed bug (knots)", HasParam: true},
	{Name: "AP_SPD_VAR_INC", Category: "Autopilot", Description: "Increase speed bug"},
	{Name: "AP_SPD_VAR_DEC", Category: "Autopilot", Description: "Decrease speed bug"},
	{Name: "AP_MACH_HOLD", Category: "Autopilot", Description: "Toggle mach hold mode"},
	{Name: "AP_MACH_VAR_SET", Category: "Autopilot", Description: "Set mach bug", HasParam: true},
	{Name: "AP_WING_LEVELER", Category: "Autopilot", Description: "Toggle wing leveler"},
	{Name: "FLIGHT_LEVEL_CHANGE", Category: "Autopilot", Description: "Toggle flight level change mode"},
	{Name: "AP_LNAV_HOLD", Category: "Autopilot", Description: "Toggle LNAV mode"},
	{Name: "AP_VNAV_HOLD", Category: "Autopilot", Description: "Toggle VNAV mode"},
	{Name: "TOGGLE_FLIGHT_DIRECTOR", Category: "Autopilot", Description: "Toggle flight director"},
	{Name: "AUTO_THROTTLE_ARM", Category: "Autopilot", Description: "Arm autothrottle"},
	{Name: "AUTO_THROTTLE_TO_GA", Category: "Autopilot", Description: "Takeoff/Go-around thrust"},
	{Name: "AUTOPILOT_DISENGAGE_TOGGLE", Category: "Autopilot", Description: "Toggle autopilot disconnect"},
	{Name: "AP_BC_HOLD", Category: "Autopilot", Description: "Toggle back course hold"},
	{Name: "AP_BC_HOLD_ON", Category: "Autopilot", Description: "Turn back course hold on"},
	{Name: "AP_BC_HOLD_OFF", Category: "Autopilot", Description: "Turn back course hold off"},
	{Name: "YAW_DAMPER_TOGGLE", Category: "Autopilot", Description: "Toggle yaw damper"},
	{Name: "YAW_DAMPER_ON", Category: "Autopilot", Description: "Turn yaw damper on"},
	{Name: "YAW_DAMPER_OFF", Category: "Autopilot", Description: "Turn yaw damper off"},

	// Electrical
	{Name: "TOGGLE_MASTER_BATTERY", Category: "Electrical", Description: "Toggle master battery"},
	{Name: "TOGGLE_MASTER_ALTERNATOR", Category: "Electrical", Description: "Toggle master alternator"},
	{Name: "TOGGLE_MASTER_BATTERY_ALTERNATOR", Category: "Electrical", Description: "Toggle battery and alternator together"},
	{Name: "AVIONICS_MASTER_SET", Category: "Electrical", Description: "Toggle avionics master"},
	{Name: "AVIONICS_MASTER_1_ON", Category: "Electrical", Description: "Turn avionics master on"},
	{Name: "AVIONICS_MASTER_1_OFF", Category: "Electrical", Description: "Turn avionics master off"},
	{Name: "TOGGLE_ELECTRIC_VACUUM_PUMP", Category: "Electrical", Description: "Toggle electric vacuum pump"},
	{Name: "TOGGLE_ALTERNATE_STATIC", Category: "Electrical", Description: "Toggle alternate static source"},

	// Lights
	{Name: "LANDING_LIGHTS_ON", Category: "Lights", Description: "Turn landing lights on"},
	{Name: "LANDING_LIGHTS_OFF", Category: "Lights", Description: "Turn landing lights off"},
	{Name: "LANDING_LIGHTS_TOGGLE", Category: "Lights", Description: "Toggle landing lights"},
	{Name: "STROBES_ON", Category: "Lights", Description: "Turn strobe lights on"},
	{Name: "STROBES_OFF", Category: "Lights", Description: "Turn strobe lights off"},
	{Name: "STROBES_TOGGLE", Category: "Lights", Description: "Toggle strobe lights"},
	{Name: "NAV_LIGHTS_ON", Category: "Lights", Description: "Turn nav lights on"},
	{Name: "NAV_LIGHTS_OFF", Category: "Lights", Description: "Turn nav lights off"},
	{Name: "TOGGLE_NAV_LIGHTS", Category: "Lights", Description: "Toggle nav lights"},
	{Name: "BEACON_LIGHTS_ON", Category: "Lights", Description: "Turn beacon on"},
	{Name: "BEACON_LIGHTS_OFF", Category: "Lights", Description: "Turn beacon off"},
	{Name: "TOGGLE_BEACON_LIGHTS", Category: "Lights", Description: "Toggle beacon"},
	{Name: "TAXI_LIGHTS_ON", Category: "Lights", Description: "Turn taxi lights on"},
	{Name: "TAXI_LIGHTS_OFF", Category: "Lights", Description: "Turn taxi lights off"},
	{Name: "TOGGLE_TAXI_LIGHTS", Category: "Lights", Description: "Toggle taxi lights"},
	{Name: "ALL_LIGHTS_TOGGLE", Category: "Lights", Description: "Toggle all lights"},
	{Name: "TOGGLE_CABIN_LIGHTS", Category: "Lights", Description: "Toggle cabin lights"},
	{Name: "PANEL_LIGHTS_ON", Category: "Lights", Description: "Turn panel lights on"},
	{Name: "PANEL_LIGHTS_OFF", Category: "Lights", Description: "Turn panel lights off"},
	{Name: "PANEL_LIGHTS_TOGGLE", Category: "Lights", Description: "Toggle panel lights"},
	{Name: "TOGGLE_WING_LIGHTS", Category: "Lights", Description: "Toggle wing lights"},
	{Name: "TOGGLE_LOGO_LIGHTS", Category: "Lights", Description: "Toggle logo lights"},
	{Name: "TOGGLE_RECOGNITION_LIGHTS", Category: "Lights", Description: "Toggle recognition lights"},

	// Radio/Nav
	{Name: "COM_STBY_RADIO_SWAP", Category: "Radio", Description: "Swap COM1 active/standby"},
	{Name: "COM2_RADIO_SWAP", Category: "Radio", Description: "Swap COM2 active/standby"},
	{Name: "NAV1_RADIO_SWAP", Category: "Radio", Description: "Swap NAV1 active/standby"},
	{Name: "NAV2_RADIO_SWAP", Category: "Radio", Description: "Swap NAV2 active/standby"},
	{Name: "COM_RADIO_SET", Category: "Radio", Description: "Set COM1 frequency (BCD16)", HasParam: true},
	{Name: "COM_STBY_RADIO_SET", Category: "Radio", Description: "Set COM1 standby frequency (BCD16)", HasParam: true},
	{Name: "COM2_RADIO_SET", Category: "Radio", Description: "Set COM2 frequency (BCD16)", HasParam: true},
	{Name: "COM2_STBY_RADIO_SET", Category: "Radio", Description: "Set COM2 standby frequency (BCD16)", HasParam: true},
	{Name: "NAV1_RADIO_SET", Category: "Radio", Description: "Set NAV1 frequency (BCD16)", HasParam: true},
	{Name: "NAV1_STBY_SET", Category: "Radio", Description: "Set NAV1 standby frequency (BCD16)", HasParam: true},
	{Name: "NAV2_RADIO_SET", Category: "Radio", Description: "Set NAV2 frequency (BCD16)", HasParam: true},
	{Name: "NAV2_STBY_SET", Category: "Radio", Description: "Set NAV2 standby frequency (BCD16)", HasParam: true},
	{Name: "ADF_SET", Category: "Radio", Description: "Set ADF frequency (BCD16)", HasParam: true},
	{Name: "ADF_STBY_SET", Category: "Radio", Description: "Set ADF standby frequency", HasParam: true},
	{Name: "XPNDR_SET", Category: "Radio", Description: "Set transponder code (BCD16)", HasParam: true},
	{Name: "XPNDR_IDENT_ON", Category: "Radio", Description: "Transponder ident"},
	{Name: "XPNDR_IDENT_OFF", Category: "Radio", Description: "Transponder ident off"},
	{Name: "BAROMETRIC_PRESSURE", Category: "Radio", Description: "Set altimeter barometric pressure"},
	{Name: "KOHLSMAN_SET", Category: "Radio", Description: "Set altimeter to value (mb * 16)", HasParam: true},
	{Name: "KOHLSMAN_INC", Category: "Radio", Description: "Increase altimeter setting"},
	{Name: "KOHLSMAN_DEC", Category: "Radio", Description: "Decrease altimeter setting"},
	{Name: "DME_SELECT", Category: "Radio", Description: "Toggle DME between NAV1/NAV2", HasParam: true},
	{Name: "OBS1_SET", Category: "Radio", Description: "Set OBS 1 heading (degrees)", HasParam: true},
	{Name: "OBS2_SET", Category: "Radio", Description: "Set OBS 2 heading (degrees)", HasParam: true},

	// GPS
	{Name: "GPS_OBS_SET", Category: "GPS", Description: "Set GPS OBS mode heading", HasParam: true},
	{Name: "GPS_OBS_ON", Category: "GPS", Description: "Turn GPS OBS mode on"},
	{Name: "GPS_OBS_OFF", Category: "GPS", Description: "Turn GPS OBS mode off"},
	{Name: "GPS_ACTIVATE_WP", Category: "GPS", Description: "Activate GPS waypoint"},
	{Name: "GPS_DIRECT_TO", Category: "GPS", Description: "GPS direct-to active waypoint"},
	{Name: "TOGGLE_GPS_DRIVES_NAV1", Category: "GPS", Description: "Toggle whether GPS drives NAV1"},

	// Instruments
	{Name: "HEADING_GYRO_SET", Category: "Instruments", Description: "Set heading gyro to value (degrees)", HasParam: true},
	{Name: "GYRO_DRIFT_SET", Category: "Instruments", Description: "Set gyro drift rate", HasParam: true},
	{Name: "ATTITUDE_BARS_POSITION_SET", Category: "Instruments", Description: "Set attitude indicator bars position", HasParam: true},

	// Cabin/Doors
	{Name: "TOGGLE_CABIN_LIGHTS", Category: "Cabin", Description: "Toggle cabin lights"},
	{Name: "CABIN_SEATBELTS_ALERT_SWITCH_TOGGLE", Category: "Cabin", Description: "Toggle seatbelt sign"},
	{Name: "CABIN_NO_SMOKING_ALERT_SWITCH_TOGGLE", Category: "Cabin", Description: "Toggle no smoking sign"},
	{Name: "TOGGLE_AIRCRAFT_EXIT", Category: "Cabin", Description: "Toggle aircraft door/exit"},
	{Name: "TOGGLE_WING_FOLD", Category: "Cabin", Description: "Toggle wing fold (carrier ops)"},
	{Name: "TOGGLE_TAIL_HOOK_HANDLE", Category: "Cabin", Description: "Toggle tailhook"},
	{Name: "TOGGLE_WATER_RUDDER", Category: "Cabin", Description: "Toggle water rudder (seaplane)"},

	// Pressurization
	{Name: "PRESSURIZATION_PRESSURE_ALT_SET", Category: "Pressurization", Description: "Set cabin pressure altitude (feet)", HasParam: true},
	{Name: "PRESSURIZATION_CLIMB_RATE_SET", Category: "Pressurization", Description: "Set cabin climb rate (fpm)", HasParam: true},
	{Name: "PRESSURIZATION_PRESSURE_DUMP_SWITCH", Category: "Pressurization", Description: "Toggle pressure dump valve"},

	// Views
	{Name: "VIEW_MODE", Category: "Views", Description: "Cycle view mode"},
	{Name: "VIEW_COCKPIT_FORWARD", Category: "Views", Description: "Cockpit forward view"},
	{Name: "VIEW_VIRTUAL_COCKPIT_FORWARD", Category: "Views", Description: "Virtual cockpit forward"},
	{Name: "VIEW_FORWARD", Category: "Views", Description: "Forward view"},
	{Name: "VIEW_FORWARD_RIGHT", Category: "Views", Description: "Forward right view"},
	{Name: "VIEW_RIGHT", Category: "Views", Description: "Right view"},
	{Name: "VIEW_REAR_RIGHT", Category: "Views", Description: "Rear right view"},
	{Name: "VIEW_REAR", Category: "Views", Description: "Rear view"},
	{Name: "VIEW_REAR_LEFT", Category: "Views", Description: "Rear left view"},
	{Name: "VIEW_LEFT", Category: "Views", Description: "Left view"},
	{Name: "VIEW_FORWARD_LEFT", Category: "Views", Description: "Forward left view"},
	{Name: "VIEW_DOWN", Category: "Views", Description: "Down view"},
	{Name: "VIEW_UP", Category: "Views", Description: "Up view"},
	{Name: "ZOOM_IN", Category: "Views", Description: "Zoom in"},
	{Name: "ZOOM_OUT", Category: "Views", Description: "Zoom out"},
	{Name: "PAN_LEFT", Category: "Views", Description: "Pan camera left"},
	{Name: "PAN_RIGHT", Category: "Views", Description: "Pan camera right"},
	{Name: "PAN_UP", Category: "Views", Description: "Pan camera up"},
	{Name: "PAN_DOWN", Category: "Views", Description: "Pan camera down"},

	// ATC
	{Name: "ATC_MENU_OPEN", Category: "ATC", Description: "Open ATC menu"},
	{Name: "ATC_MENU_CLOSE", Category: "ATC", Description: "Close ATC menu"},
	{Name: "ATC1", Category: "ATC", Description: "Select ATC option 1"},
	{Name: "ATC2", Category: "ATC", Description: "Select ATC option 2"},
	{Name: "ATC3", Category: "ATC", Description: "Select ATC option 3"},
	{Name: "ATC4", Category: "ATC", Description: "Select ATC option 4"},
	{Name: "ATC5", Category: "ATC", Description: "Select ATC option 5"},
	{Name: "ATC6", Category: "ATC", Description: "Select ATC option 6"},
	{Name: "ATC7", Category: "ATC", Description: "Select ATC option 7"},
	{Name: "ATC8", Category: "ATC", Description: "Select ATC option 8"},

	// Simulation
	{Name: "PAUSE_TOGGLE", Category: "Simulation", Description: "Toggle pause"},
	{Name: "PAUSE_ON", Category: "Simulation", Description: "Pause simulation"},
	{Name: "PAUSE_OFF", Category: "Simulation", Description: "Unpause simulation"},
	{Name: "PAUSE_SET", Category: "Simulation", Description: "Set pause state (1=pause, 0=unpause)", HasParam: true},
	{Name: "SIM_RATE_INCR", Category: "Simulation", Description: "Increase sim rate"},
	{Name: "SIM_RATE_DECR", Category: "Simulation", Description: "Decrease sim rate"},
	{Name: "SIM_RATE_SET", Category: "Simulation", Description: "Set sim rate multiplier", HasParam: true},
	{Name: "FREEZE_LATITUDE_LONGITUDE_TOGGLE", Category: "Simulation", Description: "Freeze position"},
	{Name: "FREEZE_LATITUDE_LONGITUDE_SET", Category: "Simulation", Description: "Set position freeze (1=on, 0=off)", HasParam: true},
	{Name: "FREEZE_ALTITUDE_TOGGLE", Category: "Simulation", Description: "Freeze altitude"},
	{Name: "FREEZE_ALTITUDE_SET", Category: "Simulation", Description: "Set altitude freeze (1=on, 0=off)", HasParam: true},
	{Name: "FREEZE_ATTITUDE_TOGGLE", Category: "Simulation", Description: "Freeze attitude"},
	{Name: "FREEZE_ATTITUDE_SET", Category: "Simulation", Description: "Set attitude freeze (1=on, 0=off)", HasParam: true},

	// Flight Plans
	{Name: "FLIGHT_PLAN_ACTIVATE", Category: "Flight Plan", Description: "Activate loaded flight plan"},
	{Name: "FLIGHT_PLAN_DEACTIVATE", Category: "Flight Plan", Description: "Deactivate flight plan"},

	// Helicopter
	{Name: "ROTOR_BRAKE", Category: "Helicopter", Description: "Toggle rotor brake"},
	{Name: "GOVERNOR_SWITCH_TOGGLE", Category: "Helicopter", Description: "Toggle governor"},
	{Name: "ROTOR_CLUTCH_SWITCH_TOGGLE", Category: "Helicopter", Description: "Toggle rotor clutch"},
	{Name: "COLLECTIVE_INCR", Category: "Helicopter", Description: "Increase collective"},
	{Name: "COLLECTIVE_DECR", Category: "Helicopter", Description: "Decrease collective"},
	{Name: "COLLECTIVE_SET", Category: "Helicopter", Description: "Set collective position (0-16383)", HasParam: true},
	{Name: "HELI_BEEP_INCREASE", Category: "Helicopter", Description: "Increase governor RPM"},
	{Name: "HELI_BEEP_DECREASE", Category: "Helicopter", Description: "Decrease governor RPM"},

	// Weight/Balance
	{Name: "PAYLOAD_STATION_WEIGHT_SET", Category: "Weight", Description: "Set payload station weight (lbs) — param is station:weight encoded", HasParam: true},

	// Flight Control Axes
	{Name: "AILERON_SET", Category: "Controls", Description: "Set aileron position (-16383 to 16383)", HasParam: true},
	{Name: "ELEVATOR_SET", Category: "Controls", Description: "Set elevator position (-16383 to 16383)", HasParam: true},
	{Name: "RUDDER_SET", Category: "Controls", Description: "Set rudder position (-16383 to 16383)", HasParam: true},
	{Name: "AXIS_AILERON_SET", Category: "Controls", Description: "Set aileron axis (-16383 to 16383)", HasParam: true},
	{Name: "AXIS_ELEVATOR_SET", Category: "Controls", Description: "Set elevator axis (-16383 to 16383)", HasParam: true},
	{Name: "AXIS_RUDDER_SET", Category: "Controls", Description: "Set rudder axis (-16383 to 16383)", HasParam: true},

	// Cowl Flaps
	{Name: "COWLFLAP1_SET", Category: "Engine", Description: "Set engine 1 cowl flap position (0-16383)", HasParam: true},
	{Name: "COWLFLAP2_SET", Category: "Engine", Description: "Set engine 2 cowl flap position (0-16383)", HasParam: true},
	{Name: "INC_COWL_FLAPS", Category: "Engine", Description: "Open cowl flaps one step"},
	{Name: "DEC_COWL_FLAPS", Category: "Engine", Description: "Close cowl flaps one step"},

	// Slew
	{Name: "SLEW_ON", Category: "Slew", Description: "Enable slew mode"},
	{Name: "SLEW_OFF", Category: "Slew", Description: "Disable slew mode"},
	{Name: "SLEW_TOGGLE", Category: "Slew", Description: "Toggle slew mode"},
	{Name: "SLEW_SET", Category: "Slew", Description: "Set slew mode (1=on, 0=off)", HasParam: true},
	{Name: "SLEW_AHEAD_PLUS", Category: "Slew", Description: "Slew forward"},
	{Name: "SLEW_AHEAD_MINUS", Category: "Slew", Description: "Slew backward"},
	{Name: "SLEW_LEFT", Category: "Slew", Description: "Slew left"},
	{Name: "SLEW_RIGHT", Category: "Slew", Description: "Slew right"},
	{Name: "SLEW_UP", Category: "Slew", Description: "Slew up"},
	{Name: "SLEW_DOWN", Category: "Slew", Description: "Slew down"},
	{Name: "SLEW_HEADING_PLUS", Category: "Slew", Description: "Rotate heading right in slew"},
	{Name: "SLEW_HEADING_MINUS", Category: "Slew", Description: "Rotate heading left in slew"},

	// Time
	{Name: "ZULU_HOURS_SET", Category: "Time", Description: "Set zulu time hours (0-23)", HasParam: true},
	{Name: "ZULU_MINUTES_SET", Category: "Time", Description: "Set zulu time minutes (0-59)", HasParam: true},
	{Name: "ZULU_DAY_SET", Category: "Time", Description: "Set zulu day of year (1-365)", HasParam: true},
	{Name: "ZULU_YEAR_SET", Category: "Time", Description: "Set zulu year", HasParam: true},
	{Name: "CLOCK_HOURS_SET", Category: "Time", Description: "Set local clock hours", HasParam: true},
	{Name: "CLOCK_MINUTES_SET", Category: "Time", Description: "Set local clock minutes", HasParam: true},

	// Failures (training scenarios)
	{Name: "TOGGLE_ENGINE1_FAILURE", Category: "Failures", Description: "Toggle engine 1 failure"},
	{Name: "TOGGLE_ENGINE2_FAILURE", Category: "Failures", Description: "Toggle engine 2 failure"},
	{Name: "TOGGLE_ELECTRICAL_FAILURE", Category: "Failures", Description: "Toggle electrical system failure"},
	{Name: "TOGGLE_PITOT_BLOCKAGE", Category: "Failures", Description: "Toggle pitot tube blockage"},
	{Name: "TOGGLE_STATIC_PORT_BLOCKAGE", Category: "Failures", Description: "Toggle static port blockage"},
	{Name: "TOGGLE_HYDRAULIC_FAILURE", Category: "Failures", Description: "Toggle hydraulic system failure"},
	{Name: "TOGGLE_BRAKE_FAILURE", Category: "Failures", Description: "Toggle brake failure"},
	{Name: "TOGGLE_VACUUM_FAILURE", Category: "Failures", Description: "Toggle vacuum system failure"},

	// Seaplane/Floats
	{Name: "TOGGLE_WATER_BALLAST_VALVE", Category: "Seaplane", Description: "Toggle water ballast valve"},
	{Name: "TOGGLE_WATER_RUDDER", Category: "Seaplane", Description: "Toggle water rudder"},
}
